In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
path = "newdata/DVSGesture/ibmGestureTrain/user01_fluorescent/0.npy"
events = np.load(path)

In [4]:
print(events.dtype)
print(events.shape)
print("Fields:", events.dtype.names)

float64
(213025, 4)
Fields: None


In [5]:
print("Shape:", events.shape)
print("Dtype:", events.dtype)
print("First 5 rows:\n", events[:5])


Shape: (213025, 4)
Dtype: float64
First 5 rows:
 [[4.9e+01 8.2e+01 0.0e+00 2.8e-02]
 [5.5e+01 9.2e+01 1.0e+00 3.8e-02]
 [5.5e+01 9.2e+01 1.0e+00 3.9e-02]
 [5.5e+01 9.2e+01 1.0e+00 3.9e-02]
 [9.0e+01 9.9e+01 0.0e+00 6.5e-02]]


In [7]:
x = events[:, 0].astype(int)
y = events[:, 1].astype(int)
p = events[:, 2].astype(int)
t_norm = events[:, 3]   # values in [0,1]


In [9]:
dt = np.diff(t_norm)
print("Median Δt:", np.median(dt))
print("Mean Δt:", dt.mean())
print("Min Δt:", dt.min())
print("Max Δt:", dt.max())
print("99th percentile:", np.percentile(dt, 99))


Median Δt: 0.012999999999919964
Mean Δt: 0.02368011585549046
Min Δt: 0.0
Max Δt: 1.3229999999994106
99th percentile: 0.15977000000000632


In [10]:
dt = np.diff(events[:, 3])
print("Median Δt:", np.median(dt))
print("Mean Δt:", dt.mean())
print("99 percentile:", np.percentile(dt, 99))
print("Max Δt:", dt.max())

Median Δt: 0.012999999999919964
Mean Δt: 0.02368011585549046
99 percentile: 0.15977000000000632
Max Δt: 1.3229999999994106
